// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6NgTOE8j6SAwNOW-AWWB3cs-FRbuyMQ',
    appId: '1:1002846516261:web:2f0ffc704697419314bbcc',
    messagingSenderId: '1002846516261',
    projectId: 'myapp-d71ab',
    authDomain: 'myapp-d71ab.firebaseapp.com',
    storageBucket: 'myapp-d71ab.appspot.com',
    measurementId: 'G-DQZJHXRJ1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5tvTK6H70AzOWlsgWEDwPcFTwn9iQRU',
    appId: '1:1002846516261:android:611cdb075f43ccd314bbcc',
    messagingSenderId: '1002846516261',
    projectId: 'myapp-d71ab',
    storageBucket: 'myapp-d71ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_PzB43OZD8lCrLLJRhkfOnfpwB0NoWc',
    appId: '1:1002846516261:ios:4262879e0cc298fb14bbcc',
    messagingSenderId: '1002846516261',
    projectId: 'myapp-d71ab',
    storageBucket: 'myapp-d71ab.appspot.com',
    iosClientId: '1002846516261-ab0kt2dqesl6351vk65q4tq1i8mkr170.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_PzB43OZD8lCrLLJRhkfOnfpwB0NoWc',
    appId: '1:1002846516261:ios:4262879e0cc298fb14bbcc',
    messagingSenderId: '1002846516261',
    projectId: 'myapp-d71ab',
    storageBucket: 'myapp-d71ab.appspot.com',
    iosClientId: '1002846516261-ab0kt2dqesl6351vk65q4tq1i8mkr170.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
